name: cloudbase_ce
description: Cloudbase SDK community edition. All APIs are consistent to the official with null-safety.
version: 2.1.4
homepage: https://github.com/insightop/cloudbase_ce

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.4
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  package_info_plus: ">=4.2.0 <9.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter